[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run start"
restartPolicyType = "always"
healthcheckPath = "/api/health"
healthcheckTimeout = 30

[[services]]
name = "chain-admin-backend"