import { useMemo, useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { Link, useLocation } from "wouter";
import { Phone, LayoutDashboard, History, Voicemail, Disc3, Hash, Users, Settings, Grid2X2, Menu, X, PhoneCall, Play, Search, LogOut } from "lucide-react";
import { brands } from "@/config/brands";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { deleteCookie, persistTenantMetadata, setCookie } from "@/lib/cookies";

const brand = brands.chiamo;
const marketing = "https://chainsoftwaregroup.com";
const nav = [
  ["/dashboard", "Dashboard", LayoutDashboard], ["/phone", "Phone", Phone],
  ["/call-logs", "Call Logs", History], ["/voicemail", "Voicemail", Voicemail],
  ["/recordings", "Recordings", Disc3], ["/numbers", "Numbers", Hash],
  ["/users", "Users", Users], ["/settings", "Settings", Settings],
  ["/more-services", "More Services", Grid2X2],
] as const;

export function ChiamoFooter() {
  return <footer className="border-t border-slate-200 px-6 py-8 text-center text-sm text-slate-500">
    <p>Chiamo Connect is a product of Chain Software Group LLC.</p>
    <div className="mt-2 flex justify-center gap-5"><a href="/privacy-policy">Privacy Policy</a><a href="/terms-of-service">Terms of Service</a><a href={`mailto:${brand.supportEmail}`}>Support</a></div>
  </footer>;
}

export function ChiamoLanding() {
  const features = [[Phone,"Business Phone","Make and receive calls using your business number."],[History,"Call History","See incoming, outgoing, missed, and completed calls."],[Voicemail,"Voicemail","Manage business voicemail from one place."],[Disc3,"Call Recording","Access recordings when enabled for the account."],[Hash,"Business Numbers","Manage assigned phone numbers."],[Users,"Users","Give team members access to the phone system."]] as const;
  return <div className="min-h-screen bg-[#f7fbfa] text-slate-900"><header className="mx-auto flex max-w-6xl items-center justify-between px-5 py-6"><img src={brand.logo} className="h-11 w-auto"/><a href="/agency-login" className="font-semibold text-emerald-700">Sign In</a></header>
    <main><section className="mx-auto grid max-w-6xl items-center gap-12 px-5 py-20 md:grid-cols-2"><div><p className="mb-5 font-bold tracking-[.24em] text-emerald-600">CHIAMO CONNECT</p><h1 className="text-5xl font-black tracking-tight md:text-7xl">Business calling,<br/><span className="text-emerald-600">simplified.</span></h1><p className="mt-7 max-w-xl text-xl text-slate-600">Make and receive business calls from anywhere.</p><div className="mt-9 flex gap-4"><a href="/agency-login" className="rounded-full bg-emerald-600 px-7 py-3 font-bold text-white">Get Started</a><a href="/agency-login" className="rounded-full border border-slate-300 px-7 py-3 font-bold">Sign In</a></div></div><div className="rounded-[2.5rem] bg-gradient-to-br from-emerald-500 to-cyan-700 p-10 text-white shadow-2xl"><PhoneCall className="h-20 w-20"/><p className="mt-16 text-3xl font-bold">Your office phone.<br/>Wherever work happens.</p></div></section>
    <section className="bg-white py-20"><div className="mx-auto max-w-6xl px-5"><h2 className="text-3xl font-bold">Everything your team needs to answer the call.</h2><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{features.map(([Icon,title,text])=><article key={title} className="rounded-2xl border p-6"><Icon className="h-7 w-7 text-emerald-600"/><h3 className="mt-5 text-lg font-bold">{title}</h3><p className="mt-2 text-slate-600">{text}</p></article>)}</div></div></section>
    <section className="mx-auto max-w-6xl px-5 py-20"><p className="font-bold text-emerald-600">MORE BUSINESS TOOLS</p><h2 className="mt-3 text-3xl font-bold">Need more than business calling?</h2><p className="mt-4 text-slate-600">Explore Email &amp; SMS, Payments, Documents, and Customer Communication on the full Chain platform.</p><a href={marketing} className="mt-7 inline-block rounded-full bg-slate-900 px-7 py-3 font-bold text-white">Explore Chain Software</a></section></main><ChiamoFooter/></div>;
}

export function ChiamoLogin() {
  const [username,setUsername]=useState(""); const [password,setPassword]=useState("");
  const login=useMutation({mutationFn:async()=>{const r=await apiRequest("POST","/api/agency/login",{username,password,product:"chiamo"}); return r.json();},onSuccess:(r)=>{localStorage.setItem("authToken",r.token);setCookie("authToken",r.token);persistTenantMetadata({slug:r.tenant?.slug,name:r.tenant?.name});window.location.href="/dashboard";}});
  return <div className="flex min-h-screen flex-col bg-[#062d31]"><main className="flex flex-1 items-center justify-center px-5 py-12"><div className="w-full max-w-md rounded-3xl bg-white p-8 shadow-2xl"><img src={brand.logo} className="mx-auto h-14"/><h1 className="mt-8 text-center text-2xl font-bold">Welcome back</h1><p className="mt-2 text-center text-slate-500">Sign in to your business phone.</p><form className="mt-8 space-y-5" onSubmit={e=>{e.preventDefault();login.mutate();}}><label className="block text-sm font-semibold">Email<Input className="mt-2 h-12" type="text" value={username} onChange={e=>setUsername(e.target.value)} required/></label><label className="block text-sm font-semibold">Password<Input className="mt-2 h-12" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{login.error&&<p className="text-sm text-red-600">{(login.error as Error).message}</p>}<Button className="h-12 w-full bg-emerald-600 hover:bg-emerald-700" disabled={login.isPending}>{login.isPending?"Signing in…":"Sign In"}</Button><a className="block text-center text-sm font-semibold text-emerald-700" href="/agency/forgot-password">Forgot Password</a></form></div></main><ChiamoFooter/></div>;
}

export function ChiamoShell({page}:{page:string}) { const [open,setOpen]=useState(false); const logout=()=>{localStorage.removeItem("authToken");deleteCookie("authToken");window.location.href="/agency-login";}; return <div className="min-h-screen bg-slate-50 text-slate-900"><aside className={`${open?"translate-x-0":"-translate-x-full"} fixed inset-y-0 z-30 w-72 bg-[#062d31] p-5 text-white transition md:translate-x-0`}><div className="flex items-center justify-between"><img src={brand.logo} className="h-11 rounded bg-white p-1"/><button className="md:hidden" onClick={()=>setOpen(false)}><X/></button></div><nav className="mt-10 space-y-1">{nav.map(([href,label,Icon])=><Link key={href} href={href} onClick={()=>setOpen(false)} className={`flex items-center gap-3 rounded-xl px-4 py-3 ${page===href?"bg-emerald-500 font-bold":"text-slate-300 hover:bg-white/10"}`}><Icon className="h-5 w-5"/>{label}</Link>)}</nav></aside><div className="md:pl-72"><header className="flex h-20 items-center justify-between border-b bg-white px-5"><div className="flex items-center"><button className="mr-4 md:hidden" onClick={()=>setOpen(true)}><Menu/></button><h1 className="text-xl font-bold">{nav.find(n=>n[0]===page)?.[1]}</h1></div><Button variant="ghost" onClick={logout}><LogOut className="mr-2 h-4 w-4"/>Logout</Button></header><main className="p-4 sm:p-8"><ChiamoPage page={page}/></main></div></div> }

type Call={id:string;fromNumber:string;toNumber:string;direction:string;status:string;duration:number|null;createdAt:string;recordingUrl?:string;recordingSid?:string};
function useVoice(){const calls=useQuery<Call[]>({queryKey:["/api/voip/call-logs?limit=500"]});const numbers=useQuery<any[]>({queryKey:["/api/voip/phone-numbers"]});const users=useQuery<any[]>({queryKey:["/api/team-members"]});return {calls:calls.data||[],numbers:numbers.data||[],users:users.data||[],loading:calls.isLoading||numbers.isLoading};}
function ChiamoPage({page}:{page:string}) { const {calls,numbers,users,loading}=useVoice(); const [filter,setFilter]=useState("all"); const [search,setSearch]=useState(""); const filtered=useMemo(()=>calls.filter(c=>(filter==="all"||c.direction===filter||filter==="missed"&&c.status==="missed")&&`${c.fromNumber} ${c.toNumber}`.toLowerCase().includes(search.toLowerCase())),[calls,filter,search]); if(page==="/phone") return <div className="mx-auto max-w-xl rounded-3xl bg-[#062d31] p-8 text-center text-white"><Phone className="mx-auto h-12 w-12 text-emerald-400"/><h2 className="mt-4 text-2xl font-bold">Business Phone</h2><p className="mt-2 text-slate-300">Open the shared, secure calling experience.</p><Button className="mt-8 bg-emerald-500" onClick={()=>window.open('/softphone','_blank','width=400,height=700')}>Open Phone</Button></div>;
  if(page==="/dashboard") {const today=new Date().toDateString();const todays=calls.filter(c=>new Date(c.createdAt).toDateString()===today);return <div className="grid gap-6 lg:grid-cols-3"><Card title="BUSINESS PHONE"><p className="text-2xl font-bold">{numbers[0]?.phoneNumber||"No number assigned"}</p><p className="text-emerald-600">{numbers.length?"Ready":"Setup required"}</p><a href="/phone" className="mt-5 inline-block font-bold text-emerald-700">Open Phone →</a></Card><Card title="TODAY"><div className="grid grid-cols-3 gap-2 text-center"><Metric n={todays.filter(c=>c.direction==="incoming").length} t="Incoming"/><Metric n={todays.filter(c=>c.direction==="outgoing").length} t="Outgoing"/><Metric n={todays.filter(c=>c.status==="missed").length} t="Missed"/></div></Card><Card title="USERS"><p className="text-4xl font-black">{users.filter(u=>u.voipAccess).length}</p><p className="text-slate-500">Active phone users</p></Card><div className="lg:col-span-2"><Card title="RECENT CALLS"><CallTable calls={calls.slice(0,5)}/></Card></div><Card title="QUICK ACTIONS"><div className="grid gap-2">{[["Make Call","/phone"],["View Call Logs","/call-logs"],["Listen to Voicemail","/voicemail"],["Manage Numbers","/numbers"]].map(x=><a className="rounded-xl bg-slate-100 p-3 font-semibold" href={x[1]}>{x[0]}</a>)}</div></Card></div>}
  if(page==="/call-logs"||page==="/recordings"){const shown=page==="/recordings"?filtered.filter(c=>c.recordingSid||c.recordingUrl):filtered;return <Card title={page==="/recordings"?"CALL RECORDINGS":"CALL HISTORY"}><div className="mb-5 flex flex-wrap gap-2"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4"/><Input className="pl-9" placeholder="Search number or name" value={search} onChange={e=>setSearch(e.target.value)}/></div>{["all","incoming","outgoing","missed"].map(f=><Button variant={filter===f?"default":"outline"} onClick={()=>setFilter(f)}>{f[0].toUpperCase()+f.slice(1)}</Button>)}</div><CallTable calls={shown} recordings={page==="/recordings"}/></Card>}
  if(page==="/numbers") return <Card title="BUSINESS NUMBERS"><SimpleTable heads={["Phone Number","Assigned User / Extension","Status","Capabilities"]} rows={numbers.map(n=>[n.phoneNumber,n.friendlyName||"Unassigned",n.isActive?"Active":"Inactive","Voice"])} empty="No business numbers are assigned."/></Card>;
  if(page==="/users") return <Card title="VOICE USERS"><SimpleTable heads={["Name","Email","Role","Status","VoIP Access"]} rows={users.map(u=>[u.name||u.username,u.email,u.role,u.isActive===false?"Inactive":"Active",u.voipAccess?"Enabled":"Disabled"])} empty="No users found."/></Card>;
  if(page==="/voicemail") return <Card title="VOICEMAIL"><Voicemail className="h-10 w-10 text-emerald-600"/><h2 className="mt-4 text-xl font-bold">Voicemail is not available yet</h2><p className="mt-2 text-slate-500">The shared backend does not currently expose voicemail storage or management. No simulated messages are shown.</p></Card>;
  if(page==="/more-services") return <div><h2 className="text-3xl font-bold">More tools for growing businesses</h2><div className="mt-6 grid gap-5 md:grid-cols-2">{[["EMAIL & SMS","Reach customers through email and text campaigns."],["PAYMENTS","Accept and manage customer payments."],["DOCUMENTS","Send and manage business documents."],["FULL CHAIN PLATFORM","Combine communication, payments, documents, and more."]].map(([t,d])=><Card title={t}><p className="text-slate-600">{d}</p><a href={marketing} className="mt-5 inline-block font-bold text-emerald-700">{t==="FULL CHAIN PLATFORM"?"Explore Chain":"Learn More"} →</a></Card>)}</div></div>;
  return <div className="grid gap-5 md:grid-cols-2">{["My Profile","Phone Settings","Voicemail","Notifications","Users & Permissions","Organization","Billing","More Services"].map(t=><Card title={t}><p className="text-slate-500">Manage {t.toLowerCase()} with the controls supported for your account.</p></Card>)}</div>;
}
function Card({title,children}:{title:string;children:any}){return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="mb-5 text-xs font-black tracking-[.16em] text-slate-500">{title}</h3>{children}</section>}; function Metric({n,t}:{n:number;t:string}){return <div><p className="text-3xl font-black">{n}</p><p className="text-xs text-slate-500">{t}</p></div>}
function CallTable({calls,recordings=false}:{calls:Call[];recordings?:boolean}){return <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead><tr className="border-b text-slate-500">{["Caller / Recipient","Direction","Status","Duration","Date / Time",recordings?"Recording":""].map(x=><th className="p-3">{x}</th>)}</tr></thead><tbody>{calls.map(c=><tr className="border-b last:border-0"><td className="p-3 font-semibold">{c.direction==="incoming"?c.fromNumber:c.toNumber}</td><td className="p-3 capitalize">{c.direction}</td><td className="p-3 capitalize">{c.status}</td><td className="p-3">{c.duration?`${Math.floor(c.duration/60)}:${String(c.duration%60).padStart(2,"0")}`:"—"}</td><td className="p-3">{new Date(c.createdAt).toLocaleString()}</td><td className="p-3">{recordings&&(c.recordingSid||c.recordingUrl)?<a className="text-emerald-700" href={`/api/voip/recording/${c.recordingSid}`}><Play className="h-4 w-4"/></a>:null}</td></tr>)}</tbody></table>{!calls.length&&<p className="py-10 text-center text-slate-500">No call activity found.</p>}</div>}
function SimpleTable({heads,rows,empty}:{heads:string[];rows:any[][];empty:string}){return <div className="overflow-x-auto"><table className="w-full min-w-[600px] text-left text-sm"><thead><tr className="border-b">{heads.map(h=><th className="p-3 text-slate-500">{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr className="border-b" key={i}>{r.map(c=><td className="p-3">{String(c??"—")}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="py-10 text-center text-slate-500">{empty}</p>}</div>}
