import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Copy, UserPlus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { queryClient } from "@/lib/queryClient";

type Member = { id:string; username:string; email:string; firstName:string|null; lastName:string|null; role:string; isActive:boolean; voipAccess:boolean };
type SeatPrice = {activeUsers:number;includedUsers:number|null;monthlyAdditionalUserChargeCents:number|null};
type Response = { members:Member[]; permissions:{canManageUsers:boolean}; seats:SeatPrice&{maxActiveUsers:number;nextSeat:SeatPrice|null} };
type MemberUpdate = { id:string; email?:string; firstName?:string|null; lastName?:string|null; role?:string; voipAccess?:boolean; isActive?:boolean; confirmSeatPriceImpact?:boolean };
const money=(n:number|null)=>n==null?"Pending":`$${(n/100).toFixed(2)}`;
async function request(url:string, method="GET", body?:unknown) { const token=localStorage.getItem("authToken"); const r=await fetch(url,{method,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})},body:body?JSON.stringify(body):undefined}); const data=await r.json().catch(()=>({})); if(!r.ok) throw new Error(data.message||"Unable to manage users"); return data; }
export function chiamoActivationPayload(member:Pick<Member,"id"|"isActive">):MemberUpdate {
  return member.isActive ? {id:member.id,isActive:false} : {id:member.id,isActive:true,confirmSeatPriceImpact:true};
}

export function ChiamoUsersPanel() {
  const users=useQuery<Response>({queryKey:["/api/chiamo/team-members"],queryFn:()=>request("/api/chiamo/team-members")});
  const [error,setError]=useState(""); const [issued,setIssued]=useState<{username:string;temporaryPassword:string;expiresAt:string}|null>(null);
  const [editing,setEditing]=useState<Member|null>(null);
  const [form,setForm]=useState({username:"",email:"",firstName:"",lastName:"",role:"agent",voipAccess:false,ownerPassword:"",confirmSeatPriceImpact:false});
  const save=useMutation({mutationFn:()=>request("/api/chiamo/team-members","POST",form),onSuccess:(data)=>{setIssued(data.credentials);setForm({username:"",email:"",firstName:"",lastName:"",role:"agent",voipAccess:false,ownerPassword:"",confirmSeatPriceImpact:false});queryClient.invalidateQueries({queryKey:["/api/chiamo/team-members"]})},onError:(e:Error)=>setError(e.message)});
  const edit=useMutation({mutationFn:({id,...body}:MemberUpdate)=>request(`/api/chiamo/team-members/${id}`,"PATCH",body),onSuccess:()=>{setEditing(null);setError("");queryClient.invalidateQueries({queryKey:["/api/chiamo/team-members"]})},onError:(e:Error)=>setError(e.message)});
  if(users.isLoading)return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">Loading users…</section>;
  if(users.isError)return <section className="rounded-2xl border border-red-200 bg-white p-6 text-red-700">Unable to load users. {users.error instanceof Error?users.error.message:"Please try again."}</section>;
  const seats=users.data!.seats; const charge=seats.monthlyAdditionalUserChargeCents;
  return <div className="mx-auto max-w-5xl space-y-6">
    <section className="rounded-2xl bg-[#062d31] p-6 text-white shadow-sm"><p className="text-xs font-black tracking-[.16em] text-emerald-300">TEAM MANAGEMENT</p><h2 className="mt-2 text-3xl font-black">Users & phone access</h2><p className="mt-2 text-slate-300">{seats.activeUsers} active of {seats.maxActiveUsers} available seats{charge!=null?` · additional-user charge: ${money(charge)}/month`:""}</p></section>
    {issued&&<section className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6"><h3 className="font-bold text-emerald-950">Credentials created — copy them now</h3><p className="mt-2 text-sm text-emerald-900">This temporary password is shown once and expires {new Date(issued.expiresAt).toLocaleString()}. The user must change it at sign-in.</p><div className="mt-4 flex flex-wrap items-center gap-3 rounded-xl bg-white p-4 font-mono text-sm"><span>{issued.username}: {issued.temporaryPassword}</span><Button type="button" size="sm" variant="outline" onClick={()=>navigator.clipboard.writeText(`${issued.username}: ${issued.temporaryPassword}`)}><Copy className="mr-2 h-4 w-4"/>Copy</Button><Button type="button" size="sm" variant="ghost" onClick={()=>setIssued(null)}>Dismiss</Button></div></section>}
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="text-xs font-black tracking-[.16em] text-slate-500">ADD USER</h3><form className="mt-5 grid gap-4 md:grid-cols-2" onSubmit={e=>{e.preventDefault();setError("");save.mutate()}}><Input required placeholder="Username" value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/><Input required type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><Input placeholder="First name" value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})}/><Input placeholder="Last name" value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})}/><label className="text-sm font-semibold">Role<select className="mt-2 h-10 w-full rounded-md border px-3" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{["agent","manager","viewer","uploader"].map(x=><option key={x}>{x}</option>)}</select></label><label className="flex items-center gap-3 pt-6 font-semibold"><input type="checkbox" checked={form.voipAccess} onChange={e=>setForm({...form,voipAccess:e.target.checked})}/> Enable VoIP access</label><label className="md:col-span-2"><span className="text-sm font-semibold">Confirm your owner password</span><Input className="mt-2" required type="password" autoComplete="current-password" value={form.ownerPassword} onChange={e=>setForm({...form,ownerPassword:e.target.value})}/></label>{charge!=null&&<label className="flex gap-3 text-sm md:col-span-2"><input required type="checkbox" checked={form.confirmSeatPriceImpact} onChange={e=>setForm({...form,confirmSeatPriceImpact:e.target.checked})}/> I confirm the projected monthly additional-user charge changes from {money(charge)} to {money(seats.nextSeat?.monthlyAdditionalUserChargeCents??charge)}.</label>}{error&&!editing&&<p className="text-sm text-red-700 md:col-span-2">{error}</p>}<Button className="bg-emerald-600 hover:bg-emerald-700 md:col-span-2" disabled={save.isPending}><UserPlus className="mr-2 h-4 w-4"/>{save.isPending?"Creating…":"Create user and temporary password"}</Button></form></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="text-xs font-black tracking-[.16em] text-slate-500">USERS</h3>{editing&&<form className="mt-4 grid gap-3 rounded-xl bg-slate-50 p-4 md:grid-cols-2" onSubmit={e=>{e.preventDefault();setError("");edit.mutate({id:editing.id,email:editing.email,firstName:editing.firstName||null,lastName:editing.lastName||null,role:editing.role as any,voipAccess:editing.voipAccess})}}><Input required type="email" value={editing.email} onChange={e=>setEditing({...editing,email:e.target.value})}/><select className="h-10 rounded-md border px-3" value={editing.role} onChange={e=>setEditing({...editing,role:e.target.value})}>{["agent","manager","viewer","uploader"].map(x=><option key={x}>{x}</option>)}</select><Input placeholder="First name" value={editing.firstName||""} onChange={e=>setEditing({...editing,firstName:e.target.value})}/><Input placeholder="Last name" value={editing.lastName||""} onChange={e=>setEditing({...editing,lastName:e.target.value})}/>{error&&<p className="text-sm text-red-700 md:col-span-2">{error}</p>}<div className="flex gap-2 md:col-span-2"><Button type="submit" size="sm" className="bg-emerald-600">Save changes</Button><Button type="button" size="sm" variant="ghost" onClick={()=>setEditing(null)}>Cancel</Button></div></form>}{!users.data!.members.length?<p className="py-8 text-center text-slate-500">No users found.</p>:<div className="mt-4 space-y-3">{users.data!.members.map(m=><article key={m.id} className="flex flex-wrap items-center justify-between gap-4 rounded-xl border p-4"><div><p className="font-bold">{[m.firstName,m.lastName].filter(Boolean).join(" ")||m.username} <span className="font-normal text-slate-500">({m.role})</span></p><p className="text-sm text-slate-500">{m.email} · {m.voipAccess?"VoIP enabled":"VoIP disabled"} · {m.isActive?"Active":"Inactive"}</p></div>{m.role==="owner"?<span className="text-sm text-slate-500">Owner</span>:<div className="flex gap-2"><Button size="sm" variant="outline" disabled={edit.isPending} onClick={()=>{setError("");setEditing(m)}}>Edit</Button><Button size="sm" variant="outline" disabled={edit.isPending} onClick={()=>edit.mutate({id:m.id,voipAccess:!m.voipAccess})}>{m.voipAccess?"Disable VoIP":"Enable VoIP"}</Button><Button size="sm" variant={m.isActive?"outline":"default"} disabled={edit.isPending} onClick={()=>{if(m.isActive||window.confirm(`Activating this user changes the projected monthly additional-user charge from ${money(charge)} to ${money(seats.nextSeat?.monthlyAdditionalUserChargeCents??charge)}. Continue?`))edit.mutate(chiamoActivationPayload(m))}}>{m.isActive?"Deactivate":"Activate"}</Button></div>}</article>)}</div>}</section>
  </div>;
}