import { useMutation, useQuery } from '@tanstack/react-query';
import { apiRequest, queryClient } from '@/lib/queryClient';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';

const sections = ['Overview','Companies','Voice','Primary Numbers','Local Presence','Local Presence Requests','DID Inventory','Coverage','SMS','Provider Costs','Setup / Verification'];

export function CommunicationsPanel() {
  const { data, isLoading } = useQuery<any>({ queryKey: ['/api/admin/communications'] });
  const action = useMutation({ mutationFn: ({ id, step, body }: any) => apiRequest('POST', `/api/admin/communications/requests/${id}/${step}`, body), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['/api/admin/communications'] }) });
  if (isLoading) return <div className="rounded-2xl border border-white/10 bg-white/5 p-6 text-blue-100">Loading communications…</div>;
  const requests = data?.requests || [], numbers = data?.numbers || [], companies = data?.companies || [];
  const localDids = numbers.filter((n: any) => n.numberType === 'LOCAL_PRESENCE');
  const missing = requests.filter((r: any) => ['PARTIALLY_PROVISIONED','FAILED'].includes(r.status));
  return <section id="admin-communications" className="mb-8 scroll-mt-4 space-y-5">
    <div><p className="text-xs font-semibold uppercase tracking-[.2em] text-sky-300">Chain Software Group Global Admin</p><h2 className="mt-1 text-2xl font-bold text-white">Communications / Twilio</h2></div>
    <div className="flex gap-2 overflow-x-auto">{sections.map(s => <span key={s} className="shrink-0 rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-xs text-blue-100/70">{s}</span>)}</div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[
      ['Twilio subaccounts',companies.filter((c:any)=>c.twilioAccountSid).length],['Primary Voice DIDs',numbers.filter((n:any)=>n.isPrimary).length],['Local Presence DIDs',localDids.length],['Requests',requests.length],['Awaiting approval',requests.filter((r:any)=>['COVERAGE_CALCULATED','AVAILABILITY_REVIEW','COST_REVIEW'].includes(r.status)).length],['Partially provisioned',missing.length],['Missing coverage',missing.reduce((s:number,r:any)=>s+(r.coverageRequired||[]).reduce((x:number,c:any)=>x+Math.max(0,c.need||0),0),0)],['Provider cost estimate',`$${(requests.reduce((s:number,r:any)=>s+(r.estimatedProviderCostCents||0),0)/100).toFixed(2)}`]
    ].map(([label,value])=><div key={label} className="rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-xs text-blue-100/60">{label}</p><p className="mt-2 text-2xl font-bold text-white">{value}</p></div>)}</div>
    <div className="overflow-x-auto rounded-2xl border border-white/10 bg-white/5 p-5"><h3 className="mb-4 font-semibold text-white">Local Presence Requests</h3><table className="w-full min-w-[900px] text-sm"><thead className="text-left text-blue-100/50"><tr>{['Company','Product','Package','Required / Missing','Provider cost','Customer price','Margin','Status','Actions'].map(x=><th className="pb-3 pr-4" key={x}>{x}</th>)}</tr></thead><tbody>{requests.map((r:any)=>{const company=companies.find((c:any)=>c.id===r.tenantId); const missingCount=(r.coverageRequired||[]).reduce((s:number,x:any)=>s+(x.need||0),0); return <tr className="border-t border-white/10 text-blue-50" key={r.id}><td className="py-3 pr-4">{company?.name||r.tenantId}</td><td>{r.product}</td><td>{data.packages.find((p:any)=>p.id===r.requestedPackageId)?.name}</td><td>{r.estimatedDidCount??'—'} / {missingCount}</td><td>${((r.estimatedProviderCostCents||0)/100).toFixed(2)}</td><td>${((r.customerPriceCents||0)/100).toFixed(2)}</td><td>${(((r.customerPriceCents||0)-(r.estimatedProviderCostCents||0))/100).toFixed(2)}</td><td><Badge>{r.status.replaceAll('_',' ')}</Badge></td><td><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>action.mutate({id:r.id,step:'calculate'})}>Calculate</Button><Button size="sm" variant="outline" disabled={!r.coverageRequired} onClick={()=>action.mutate({id:r.id,step:'availability'})}>Availability</Button><Button size="sm" className="bg-emerald-600" onClick={()=>window.confirm(`Approve ${r.estimatedDidCount||0} DIDs? Provider: $${((r.estimatedProviderCostCents||0)/100).toFixed(2)}, customer: $${((r.customerPriceCents||0)/100).toFixed(2)}`)&&action.mutate({id:r.id,step:'approve',body:{confirm:true}})}>Approve</Button><Button size="sm" disabled={r.status!=='APPROVED'} onClick={()=>action.mutate({id:r.id,step:'provision'})}>Provision</Button></div></td></tr>})}</tbody></table></div>
    <div className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/5 p-5"><h3 className="font-semibold text-white">SMS subaccount ownership audit</h3>{data?.ownershipAudit?.ambiguous?.length?<p className="mt-2 text-amber-300">Manual review required: duplicate subaccount references detected. No mappings were changed.</p>:<p className="mt-2 text-emerald-300">No duplicate subaccount references detected in the database.</p>}</div><div className="rounded-2xl border border-white/10 bg-white/5 p-5"><h3 className="font-semibold text-white">Voice verification</h3><p className="mt-2 text-blue-100/60">Results remain NOT TESTED / NOT VERIFIED until staff records live Twilio tests; the dashboard never infers a pass.</p></div></div>
  </section>;
}
