import { sql } from 'drizzle-orm';
import { boolean, date, integer, jsonb, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';
import { tenants } from './schema';

export const chiamoLeads = pgTable('chiamo_leads', {
  id: uuid('id').primaryKey().default(sql`gen_random_uuid()`), createdAt: timestamp('created_at').defaultNow().notNull(),
  firstName: text('first_name').notNull(), lastName: text('last_name').notNull(), businessName: text('business_name').notNull(), businessEmail: text('business_email').notNull(), businessPhone: text('business_phone').notNull(),
  employeeCount: text('employee_count'), phoneUsersNeeded: integer('phone_users_needed').notNull(), currentPhoneProvider: text('current_phone_provider'), newNumbersNeeded: integer('new_numbers_needed'), existingNumbersToPort: text('existing_numbers_to_port'), featuresNeeded: text('features_needed'),
  planInterest: text('plan_interest').notNull(), textingInterest: boolean('texting_interest').default(false).notNull(), contactPreference: text('contact_preference'), bestContactTime: text('best_contact_time'), additionalInformation: text('additional_information'),
  status: text('status').default('NEW').notNull(), assignedTo: text('assigned_to'), internalNotes: text('internal_notes'), contactHistory: jsonb('contact_history').$type<Array<{at:string;note:string}>>().default(sql`'[]'::jsonb`).notNull(),
  lastContactDate: timestamp('last_contact_date'), nextFollowUpDate: date('next_follow_up_date'), notificationStatus: text('notification_status').default('PENDING').notNull(), notificationError: text('notification_error'), notificationSentAt: timestamp('notification_sent_at'), convertedTenantId: uuid('converted_tenant_id').references(() => tenants.id),
});
export const chiamoSubscriptions = pgTable('chiamo_subscriptions', {
  tenantId: uuid('tenant_id').primaryKey().references(() => tenants.id), planId: text('plan_id').notNull(), customBasePriceCents: integer('custom_base_price_cents'), includedUsers: integer('included_users'), additionalUserPriceCents: integer('additional_user_price_cents'), additionalNumberPriceCents: integer('additional_number_price_cents').default(0).notNull(), smsAddonEnabled: boolean('sms_addon_enabled').default(false).notNull(), smsAllowance: integer('sms_allowance').default(3500).notNull(), smsOverageMicros: integer('sms_overage_micros').default(0).notNull(), customCharges: jsonb('custom_charges').$type<Array<{name:string;cents:number}>>().default(sql`'[]'::jsonb`).notNull(), discounts: jsonb('discounts').$type<Array<{name:string;cents:number}>>().default(sql`'[]'::jsonb`).notNull(), billingStatus: text('billing_status').default('PENDING_SETUP').notNull(), startDate: date('start_date'), nextBillingDate: date('next_billing_date'), notes: text('notes'), updatedAt: timestamp('updated_at').defaultNow().notNull(),
});
export const chiamoServiceConfigurations = pgTable('chiamo_service_configurations', {
  tenantId: uuid('tenant_id').primaryKey().references(() => tenants.id, { onDelete: 'cascade' }),
  accountActive: boolean('account_active').default(false).notNull(), customerLoginEnabled: boolean('customer_login_enabled').default(false).notNull(), voiceEnabled: boolean('voice_enabled').default(false).notNull(), inboundEnabled: boolean('inbound_enabled').default(false).notNull(), outboundEnabled: boolean('outbound_enabled').default(false).notNull(), recordingEnabled: boolean('recording_enabled').default(false).notNull(), voicemailEnabled: boolean('voicemail_enabled').default(false).notNull(), routingEnabled: boolean('routing_enabled').default(false).notNull(), ivrEnabled: boolean('ivr_enabled').default(false).notNull(), smsEnabled: boolean('sms_enabled').default(false).notNull(), smsStatus: text('sms_status').default('NOT_REQUESTED').notNull(),
  setupStatus: text('setup_status').default('NOT_STARTED').notNull(), setupChecklist: jsonb('setup_checklist').$type<Record<string, boolean>>().default(sql`'{}'::jsonb`).notNull(), testStatuses: jsonb('test_statuses').$type<Record<string, 'NOT_TESTED'|'PASSED'|'FAILED'>>().default(sql`'{"outbound":"NOT_TESTED","inbound":"NOT_TESTED","recording":"NOT_TESTED","voicemail":"NOT_TESTED","smsSending":"NOT_TESTED","smsReceiving":"NOT_TESTED"}'::jsonb`).notNull(), providerNotes: text('provider_notes'), internalNotes: text('internal_notes'), invitationSentAt: timestamp('invitation_sent_at'), loginConfirmedAt: timestamp('login_confirmed_at'), updatedAt: timestamp('updated_at').defaultNow().notNull(),
});
export const chiamoUsageSettings = pgTable('chiamo_usage_settings', {
  id: integer('id').primaryKey().default(1), elevatedMinutes: integer('elevated_minutes').default(3000).notNull(), highMinutes: integer('high_minutes').default(6000).notNull(), reviewMinutes: integer('review_minutes').default(10000).notNull(), voiceCostPerMinuteMicros: integer('voice_cost_per_minute_micros').default(14000).notNull(), numberCostCents: integer('number_cost_cents').default(115).notNull(), recordingCostPerMinuteMicros: integer('recording_cost_per_minute_micros').default(2500).notNull(), updatedAt: timestamp('updated_at').defaultNow().notNull(),
});
