name: EAS Build

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build for'
        required: true
        default: 'ios'
        type: choice
        options:
          - ios
          - android
          - all
      profile:
        description: 'Build profile'
        required: true
        default: 'production'
        type: choice
        options:
          - development
          - preview
          - production

jobs:
  build:
    name: Build iOS/Android App
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret in GitHub repository settings."
            echo "Get your token from: https://expo.dev/accounts/[account]/settings/access-tokens"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Sync Capacitor
        run: npx cap sync

      - name: Ensure iOS Shared Scheme Exists
        run: |
          mkdir -p ios/App/App.xcodeproj/xcshareddata/xcschemes
          if [ ! -f "ios/App/App.xcodeproj/xcshareddata/xcschemes/App.xcscheme" ]; then
            echo "Shared scheme missing after cap sync, restoring from git"
            git checkout ios/App/App.xcodeproj/xcshareddata/xcschemes/App.xcscheme
          fi

      - name: Build on EAS
        run: eas build --platform ${{ github.event.inputs.platform }} --profile ${{ github.event.inputs.profile }} --non-interactive --no-wait

      - name: Build Complete
        run: |
          echo "Build started successfully!"
          echo "Check build status at: https://expo.dev/accounts/[your-account]/projects/chain-consumer-portal/builds"
